version: "3"

services:
  app:
    container_name: ${API_CONTAINER_NAME}
    build: ../..
    env_file:
      - .env
    network_mode: host
#    ports:
#      - "8000:4443"
    command: ["python3", "main.py"]