version: "3"

services:
  app:
    container_name: ${API_CONTAINER_NAME}
    build: ../..
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - TZ=Europe/Moscow
    network_mode: host
    command: ["python3", "main.py"]
